Repository AY2021S2-CS2103-W16-3/tp, pull requests merged in 2021-03, with the labels that each got.

#64 Add new Telegram notification events to workflow
  .github/workflows/notifytele.yml
Labels: type::internal

#98 Update issue templates
  .github/ISSUE_TEMPLATE/---add-user-story.md
  .github/ISSUE_TEMPLATE/---feature-enhancement.md
Labels: type::internal

#131 Add edone command to mark Event as done
  src/main/java/seedu/partyplanet/logic/commands/EDoneCommand.java
  src/main/java/seedu/partyplanet/logic/parser/AddressBookParser.java
  src/main/java/seedu/partyplanet/logic/parser/EDoneCommandParser.java
  src/main/java/seedu/partyplanet/model/event/Event.java
  src/main/java/seedu/partyplanet/storage/JsonAdaptedEvent.java
  src/main/java/seedu/partyplanet/ui/EventCard.java
  src/main/resources/view/MainWindow.fxml
Labels: Event-branch

#143 Integration of Events into PartyPlanet
  src/main/java/seedu/partyplanet/MainApp.java
  src/main/java/seedu/partyplanet/commons/core/GuiSettings.java
  src/main/java/seedu/partyplanet/commons/core/Messages.java
  src/main/java/seedu/partyplanet/logic/Logic.java
  src/main/java/seedu/partyplanet/logic/LogicManager.java
  src/main/java/seedu/partyplanet/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/partyplanet/logic/commands/EAddCommand.java
  src/main/java/seedu/partyplanet/logic/commands/EDeleteClearCommand.java
  src/main/java/seedu/partyplanet/logic/commands/EDeleteCommand.java
  src/main/java/seedu/partyplanet/logic/commands/EDoneCommand.java
  src/main/java/seedu/partyplanet/logic/parser/AddressBookParser.java
  src/main/java/seedu/partyplanet/logic/parser/CliSyntax.java
  src/main/java/seedu/partyplanet/logic/parser/EAddCommandParser.java
  src/main/java/seedu/partyplanet/logic/parser/EDeleteCommandParser.java
  src/main/java/seedu/partyplanet/logic/parser/EDoneCommandParser.java
  src/main/java/seedu/partyplanet/model/EventBook.java
  src/main/java/seedu/partyplanet/model/Model.java
  src/main/java/seedu/partyplanet/model/ModelManager.java
  src/main/java/seedu/partyplanet/model/ReadOnlyEventBook.java
  src/main/java/seedu/partyplanet/model/UserPrefs.java
  src/main/java/seedu/partyplanet/model/event/Event.java
  src/main/java/seedu/partyplanet/model/event/UniqueEventList.java
  src/main/java/seedu/partyplanet/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/partyplanet/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/partyplanet/model/util/SampleDataUtil.java
  src/main/java/seedu/partyplanet/storage/EventBookStorage.java
  src/main/java/seedu/partyplanet/storage/JsonAdaptedEvent.java
  src/main/java/seedu/partyplanet/storage/JsonEventBookStorage.java
  src/main/java/seedu/partyplanet/storage/JsonSerializableEventBook.java
  src/main/java/seedu/partyplanet/storage/Storage.java
  src/main/java/seedu/partyplanet/storage/StorageManager.java
  src/main/java/seedu/partyplanet/ui/EventCard.java
  src/main/java/seedu/partyplanet/ui/EventListPanel.java
  src/main/java/seedu/partyplanet/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/partyplanet/logic/LogicManagerTest.java
  src/test/java/seedu/partyplanet/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/partyplanet/logic/commands/AddCommandTest.java
  src/test/java/seedu/partyplanet/logic/commands/ClearCommandTest.java
  src/test/java/seedu/partyplanet/logic/commands/CommandTestUtil.java
  src/test/java/seedu/partyplanet/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/partyplanet/logic/commands/EditCommandTest.java
  src/test/java/seedu/partyplanet/logic/commands/FindCommandTest.java
  src/test/java/seedu/partyplanet/logic/commands/ListCommandTest.java
  src/test/java/seedu/partyplanet/model/ModelManagerTest.java
  src/test/java/seedu/partyplanet/storage/StorageManagerTest.java
  src/test/java/seedu/partyplanet/testutil/EventBuilder.java
  src/test/java/seedu/partyplanet/testutil/TypicalEvents.java
Labels: type::feature::epic

#184 Enable storage of theme preferences and add submenu selection of theme
  docs/UserGuide.md
  src/main/java/seedu/partyplanet/commons/core/GuiSettings.java
  src/main/java/seedu/partyplanet/logic/commands/CommandResult.java
  src/main/java/seedu/partyplanet/logic/commands/ToggleThemeCommand.java
  src/main/java/seedu/partyplanet/ui/MainWindow.java
  src/main/java/seedu/partyplanet/ui/Theme.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/partyplanet/model/ModelManagerTest.java
  src/test/java/seedu/partyplanet/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/partyplanet/storage/StorageManagerTest.java
Labels: type::enhancement

#180 Refactor Date + Implement sort by upcoming
  src/main/java/seedu/partyplanet/logic/commands/EListCommand.java
  src/main/java/seedu/partyplanet/logic/commands/ListCommand.java
  src/main/java/seedu/partyplanet/logic/parser/EListCommandParser.java
  src/main/java/seedu/partyplanet/logic/parser/ListCommandParser.java
  src/main/java/seedu/partyplanet/model/date/Date.java
  src/main/java/seedu/partyplanet/model/event/EventDate.java
  src/main/java/seedu/partyplanet/model/person/Birthday.java
  src/main/java/seedu/partyplanet/storage/JsonAdaptedEvent.java
  src/main/java/seedu/partyplanet/ui/EventCard.java
  src/main/java/seedu/partyplanet/ui/PersonCard.java
  src/test/java/seedu/partyplanet/model/date/DateTest.java
  src/test/java/seedu/partyplanet/model/event/EventDateTest.java
  src/test/java/seedu/partyplanet/model/person/BirthdayTest.java
Labels: type::feature, type::internal

#183 Add functionality to search by birthday month
  src/main/java/seedu/partyplanet/logic/commands/ListCommand.java
  src/main/java/seedu/partyplanet/logic/parser/ListCommandParser.java
  src/main/java/seedu/partyplanet/logic/parser/ParserUtil.java
  src/main/java/seedu/partyplanet/model/date/Date.java
  src/main/java/seedu/partyplanet/model/person/predicates/BirthdayContainsMonthPredicate.java
Labels: tag::unmergeable

#195 Add image credit to README
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: type::documentation

#194 Refactor and document Undo and Redo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddStateActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/AddStateActivityDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/partyplanet/commons/util/StateHistory.java
  src/main/java/seedu/partyplanet/logic/commands/RedoCommand.java
  src/main/java/seedu/partyplanet/logic/commands/UndoCommand.java
  src/main/java/seedu/partyplanet/model/Model.java
  src/main/java/seedu/partyplanet/model/ModelManager.java
  src/main/java/seedu/partyplanet/ui/CommandBox.java
  src/test/java/seedu/partyplanet/logic/commands/AddCommandTest.java
Labels: type::documentation, type::internal

#204 Update UG, list of parameters, standardize parameter name
  docs/UserGuide.md
  src/main/java/seedu/partyplanet/logic/commands/EAddCommand.java
  src/main/java/seedu/partyplanet/logic/commands/EditCommand.java
Labels: type::documentation

#217 Change parameter list in UG into table format
  docs/UserGuide.md
Labels: type::documentation
